# Generated by Django 3.0.3 on 2020-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddConstraint(
            model_name='emojitoken',
            constraint=models.UniqueConstraint(fields=('username', 'name'), name='token_uniqueness'),
        ),
    ]
