# Generated by Django 3.1.4 on 2021-01-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('stonkgame', '0001_initial'), ('stonkgame', '0002_stonkholding_amount')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StonkGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200)),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='StonkPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='stonkgame.stonkgame')),
            ],
        ),
        migrations.CreateModel(
            name='StonkHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='stonkgame.stonkplayer')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
