# Generated by Django 3.2.2 on 2021-06-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonkgame', '0001_squashed_0002_stonkholding_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stonkholding',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
