# Generated by Django 3.0.2 on 2020-01-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=50)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
