# Generated by Django 3.0.8 on 2020-07-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
