# Generated by Django 3.1 on 2020-08-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt', models.CharField(db_index=True, max_length=255)),
                ('revoked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
