# Generated by Django 3.1 on 2020-08-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=100),
            preserve_default=False,
        ),
    ]
