# Generated by Django 3.1 on 2020-08-06 14:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apitoken_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitoken',
            name='jwt',
        ),
        migrations.AddField(
            model_name='apitoken',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
