# Generated by Django 3.0.2 on 2020-01-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=200, unique=True)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
