# Generated by Django 3.2.2 on 2021-06-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frisky', '0002_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetterStonkGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frisky.channel')),
            ],
        ),
    ]
