# Generated by Django 3.2.2 on 2021-06-25 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisky', '0002_channel'),
        ('betterstonks', '0001_squashed_0003_auto_20210624_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='betterstonkgame',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='frisky.workspace'),
        ),
    ]
