# Generated by Django 3.0.3 on 2020-02-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemeAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=30, unique=True)),
                ('meme_id', models.IntegerField()),
            ],
        ),
    ]
