# Generated by Django 3.1.4 on 2021-01-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLearn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=50, unique=True)),
                ('url', models.URLField()),
                ('element', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
