# Generated by Django 3.2.2 on 2021-06-01 13:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('SL', 'Slack'), ('NO', 'None')], max_length=2)),
                ('team_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('kind', 'team_id')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('real_name', models.CharField(max_length=100)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='frisky.workspace')),
            ],
            options={
                'unique_together': {('workspace_id', 'user_id')},
            },
        ),
    ]
